name: ev_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  web_socket_channel: ^3.0.0
  http: ^1.2.1
  crypto: ^3.0.3
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  provider: ^6.1.2
  razorpay_flutter: ^1.3.6
  flutter_dialogs: ^3.0.0
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  intl_phone_field: ^3.1.0
  curved_navigation_bar: ^1.0.1
  shimmer: ^3.0.0
  google_maps_flutter: ^2.2.0
  geolocator: ^12.0.0  
  geolocator_android: ^4.6.1
  flutter_polyline_points: ^2.1.0
  flutter_background: ^1.2.0
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  cool_alert: ^2.0.1
  url_launcher: ^6.3.0
  flutter_foreground_task: ^4.0.0
  flutter_map_marker_cluster: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Image/
    - assets/Map/map.json
    - assets/icons/Charger.png
    - assets/icons/Google_map.png
    - assets/icons/EV_location_red.png 
    - assets/icons/EV_location_green.png
    - assets/gif/loading.gif 
    - assets/gif/current_location.gif 
    